# Generated by Django 5.2.13 on 2026-04-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес (кг)'),
            preserve_default=False,
        ),
    ]
