# Generated by Django 5.2.13 on 2026-04-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='volume',
            field=models.FloatField(default=0.0, verbose_name='Объем (м³)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_volume',
            field=models.FloatField(default=0.0, verbose_name='Грузоподъемность по объему (м³)'),
        ),
    ]
