# Generated by Django 5.2.13 on 2026-05-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_order_volume_alter_order_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утвержден'), ('completed', 'Выполнен')], default='draft', max_length=10, verbose_name='Статус плана'),
        ),
    ]
