# Generated by Django 5.2.13 on 2026-05-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_deliveryplan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('planned', 'Запланирован'), ('shipped', 'В пути'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='pending', max_length=10, verbose_name='Статус заказа'),
        ),
    ]
