# Generated by Django 5.2.13 on 2026-05-17 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала ремонта/ТО')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('reason', models.CharField(default='Техническое обслуживание', max_length=255, verbose_name='Причина')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle', verbose_name='Транспорт')),
            ],
        ),
    ]
