# Generated by Django 5.2.13 on 2026-05-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_vehiclemaintenance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemaintenance',
            options={'verbose_name': 'Ремонт и ТО', 'verbose_name_plural': 'Ремонты и ТО'},
        ),
    ]
