# Generated by Django 5.2.13 on 2026-05-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_vehiclemaintenance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('urgent', 'Срочно (в указанный день)'), ('periodic', 'Периодическая')], default='urgent', max_length=10, verbose_name='Тип доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='frequency',
            field=models.CharField(choices=[('none', 'Разово'), ('weekly', 'Каждую неделю'), ('biweekly', 'Каждые 2 недели'), ('triweekly', 'Каждые 3 недели'), ('monthly', 'Раз в месяц'), ('half_yearly', 'Раз в полгода')], default='none', max_length=15, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_data',
            field=models.DateField(verbose_name='Дата доставки / Старт периода'),
        ),
    ]
