# Generated by Django 5.2.13 on 2026-05-18 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_delivery_type_order_frequency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemaintenance',
            options={},
        ),
    ]
