# Generated by Django 5.2.13 on 2026-05-19 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_actionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО Водителя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vehicle', verbose_name='Закрепленное авто')),
            ],
        ),
        migrations.CreateModel(
            name='DriverAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_type', models.CharField(choices=[('sick', 'Больничный'), ('vacation', 'Отпуск'), ('day_off', 'Отгул')], max_length=10, verbose_name='Тип отсутствия')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.driver', verbose_name='Водитель')),
            ],
        ),
    ]
