# Generated by Django 5.2.13 on 2026-05-19 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_driver_driverabsence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='planitem',
            options={},
        ),
        migrations.AddField(
            model_name='deliveryplan',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/', verbose_name='Фото сотрудника'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утвержден'), ('completed', 'Выполнен')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverabsence',
            name='end_date',
            field=models.DateField(verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='driverabsence',
            name='start_date',
            field=models.DateField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('urgent', 'Срочно (в указанный день)'), ('periodic', 'Периодическая')], default='urgent', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='frequency',
            field=models.CharField(choices=[('none', 'Разово'), ('weekly', 'Каждую неделю'), ('biweekly', 'Каждые 2 недели'), ('triweekly', 'Каждые 3 недели'), ('monthly', 'Раз в месяц'), ('half_yearly', 'Раз в полгода')], default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('planned', 'Запланирован'), ('shipped', 'В пути'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='end_date',
            field=models.DateField(verbose_name='Конец ТО'),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='start_date',
            field=models.DateField(verbose_name='Начало ТО'),
        ),
    ]
