# Generated by Django 5.2.13 on 2026-05-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_actionlog_options_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vehicle', verbose_name='Предпочтительное ТС'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='driverabsence',
            name='absence_type',
            field=models.CharField(choices=[('sick', 'Больничный'), ('vacation', 'Отпуск'), ('day_off', 'Отгул')], max_length=10),
        ),
        migrations.AlterField(
            model_name='driverabsence',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.driver'),
        ),
        migrations.AlterField(
            model_name='driverabsence',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='driverabsence',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='DriverSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('is_work_day', models.BooleanField(default=True, verbose_name='Рабочий день')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Смена водителя',
                'verbose_name_plural': 'Смены водителей',
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
