# Generated by Django 5.2.13 on 2026-05-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_driver_assigned_vehicle_alter_driver_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverschedule',
            name='end_time',
            field=models.TimeField(default='17:00', verbose_name='Конец смены'),
        ),
        migrations.AddField(
            model_name='driverschedule',
            name='start_time',
            field=models.TimeField(default='08:00', verbose_name='Начало смены'),
        ),
    ]
