# Generated by Django 5.2.13 on 2026-05-19 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_driverschedule_end_time_driverschedule_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={'verbose_name': 'Лог действия', 'verbose_name_plural': 'Журнал действий'},
        ),
        migrations.AlterModelOptions(
            name='deliveryplan',
            options={'verbose_name': 'План доставки (Рейс)', 'verbose_name_plural': 'Планы доставки (Рейсы)'},
        ),
        migrations.AlterModelOptions(
            name='driverabsence',
            options={'verbose_name': 'Отсутствие водителя', 'verbose_name_plural': 'Отсутствие водителей'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemaintenance',
            options={'verbose_name': 'Ремонт/ТО', 'verbose_name_plural': 'Ремонты и ТО'},
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(max_length=100, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='driverabsence',
            name='absence_type',
            field=models.CharField(choices=[('sick', 'Больничный'), ('vacation', 'Отпуск'), ('day_off', 'Отгул')], max_length=10, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='driverabsence',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='driverabsence',
            name='end_date',
            field=models.DateField(verbose_name='По'),
        ),
        migrations.AlterField(
            model_name='driverabsence',
            name='start_date',
            field=models.DateField(verbose_name='С'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_data',
            field=models.DateField(verbose_name='Дата доставки'),
        ),
        migrations.AlterUniqueTogether(
            name='planitem',
            unique_together={('plan', 'order')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_data', 'status'], name='main_order_deliver_55478c_idx'),
        ),
    ]
